name: Java REST API CI/CD (Docker Multistage)

on:
  push:
    branches:
      - '**'
    paths:
      - ".github/workflows/java-rest-api-ci.yaml"
      - 'templates/java-rest-api/src/**'
      - 'templates/java-rest-api/pom.xml'
      - 'templates/java-rest-api/Dockerfile'
  pull_request:
    paths:
      - ".github/workflows/java-rest-api-ci.yaml"
      - 'templates/java-rest-api/src/**'
      - 'templates/java-rest-api/pom.xml'
      - 'templates/java-rest-api/Dockerfile'

jobs:
  build:
    name: Build, Test & Package Docker
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    outputs:
      var-1: ${{ steps.vars.outputs.var-1 }}

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      # - name: Build Docker image
      #   run: docker build -t my-java-rest-api:latest templates/java-rest-api
      
      # 100% cause an issue "Skip output 'var-1' since it may contain secret.
      - name: Set var-1 (with issue)
        id: vars
        run: |
          VAR_1="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c" 
          echo var-1=$VAR_1 >> $GITHUB_OUTPUT
      
      - name: Print var-1 (with issue)
        run:
          echo ${{ steps.vars.outputs.var-1 }}
      
      - name: Set var-2 (without issue)
        id: vars2
        run: |
          VAR_2="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c" 
          echo var-2=$VAR_1 >> $GITHUB_OUTPUT
  
  deploy:
    name: Deploy
    needs: [build]
    runs-on: self-hosted

    steps:
      - name: Debug vars
        run: |
          echo ${{ needs.build.outputs.var-1 }}

  # deploy:
  #   name: Deploy to DEV
  #   runs-on: self-hosted
  #   needs: build
  #   if: github.ref == 'refs/heads/develop'

  #   steps:
  #     - name: Deploy Docker image
  #       env:
  #         DEV_SERVER: ${{ secrets.DEV_SERVER }}
  #         DEV_SSH_KEY: ${{ secrets.DEV_SSH_KEY }}
  #       run: |
  #         docker tag my-java-rest-api:latest $DEV_SERVER/my-java-rest-api:dev
  #         # Example: push to private registry or scp to server
