name: Java REST API CI/CD (Docker Multistage)

on:
  push:
    branches:
      - '**'
    paths:
      - ".github/workflows/java-rest-api-ci.yaml"
      - 'templates/java-rest-api/src/**'
      - 'templates/java-rest-api/pom.xml'
      - 'templates/java-rest-api/Dockerfile'
  pull_request:
    paths:
      - ".github/workflows/java-rest-api-ci.yaml"
      - 'templates/java-rest-api/src/**'
      - 'templates/java-rest-api/pom.xml'
      - 'templates/java-rest-api/Dockerfile'

jobs:
  build:
    name: Build, Test & Package Docker
    # runs-on: self-hosted
    outputs:
      var-1: ${{ steps.vars.outputs.var-1 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Build Docker image
      #   run: docker build -t my-java-rest-api:latest templates/java-rest-api
      
      - name: Set Vars
        id: vars
        run: |
          VAR_1=$(echo "uZem9Sow" | base64)
          echo var-1=$VAR_1 >> $GITHUB_OUTPUT
  
  deploy:
    name: Deploy
    needs: [build]
    runs-on: self-hosted

    steps:
      - name: Debug vars
        run: |
          echo ${{ needs.build.outputs.var-1 }}

  # deploy:
  #   name: Deploy to DEV
  #   runs-on: self-hosted
  #   needs: build
  #   if: github.ref == 'refs/heads/develop'

  #   steps:
  #     - name: Deploy Docker image
  #       env:
  #         DEV_SERVER: ${{ secrets.DEV_SERVER }}
  #         DEV_SSH_KEY: ${{ secrets.DEV_SSH_KEY }}
  #       run: |
  #         docker tag my-java-rest-api:latest $DEV_SERVER/my-java-rest-api:dev
  #         # Example: push to private registry or scp to server
