name: Python REST API CI

on:
  push:
    branches:
      - "**"
    paths:
      - "templates/python-rest-api/**"
      - ".github/workflows/python-rest-api-ci.yaml"

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t python-rest-api:latest templates/python-rest-api

      - name: Run tests
        run: docker run --rm python-rest-api:latest pytest tests

      - name: Build runtime image
        run: |
          docker build -f templates/python/Dockerfile -t python-rest-api:runtime templates/python-rest-api